
CREATE TABLE CAMEL_MESSAGE_IDEMPOTENT_REPOSITORY (
	MESSAGE_ID CHAR(36) NOT NULL,
	GROUP_KEY CHAR(36) NOT NULL,
	REGION VARCHAR(100) NOT NULL,
	PARTITION_KEY CHAR(36) NOT NULL,
	CREATED_DATE BIGINT NOT NULL,
	MESSAGE_PRIORITY BIGINT NOT NULL,
	MESSAGE_SEQUENCE BIGINT NOT NULL ,
	constraint CAMEL_MESSAGE_IDEMPOTENT_REPOSITORY_PK primary key (REGION, GROUP_KEY, CREATED_DATE, MESSAGE_SEQUENCE)
);

CREATE INDEX CAMEL_MESSAGE_IDEMPOTENT_REPOSITORY_DELETE_IDX ON CAMEL_MESSAGE_IDEMPOTENT_REPOSITORY (REGION, GROUP_KEY, MESSAGE_ID);
CREATE UNIQUE INDEX CAMEL_MESSAGE_IDEMPOTENT_REPOSITORY_IDX ON CAMEL_MESSAGE_IDEMPOTENT_REPOSITORY (REGION, GROUP_KEY, MESSAGE_PRIORITY DESC, CREATED_DATE, MESSAGE_SEQUENCE, PARTITION_KEY);

CREATE TABLE INT_CHANNEL_MESSAGE_PARTITION (
	GROUP_KEY CHAR(36) NOT NULL,
	REGION VARCHAR(100) NOT NULL,
	PARTITION VARCHAR(100) NOT NULL,
	CREATED_DATE BIGINT NOT NULL,
	MESSAGE_SEQUENCE BIGINT NOT NULL ,
	constraint CAMEL_MESSAGE_IDEMPOTENT_REPOSITORY_PK primary key (REGION, GROUP_KEY, CREATED_DATE, MESSAGE_SEQUENCE)
);
